apiVersion: v1
kind: Service
metadata:
    name: mynginxservice
    namespace: nginx
    labels:
       app: mynginx-svc 
spec:
  ports:
    # The port that this service should serve on.
    - port: 7654
      # port listened at inside the container
      targetPort: nginx-web-port
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: mynginx
  sessionAffinity: None
  type: NodePort