apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-web-volume"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /data/web-tier
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nginx-pv-claim"
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # to tie PVC to specific PV, specify volumeName
  # volumeName: pv-web-volume
  storageClassName: standard
---